[build]
  command = "npm run build"  # Komenda do budowania frontendu
  publish = "path/to/your/public/directory"           # Katalog, z którego Netlify będzie serwował Twoją aplikację frontendową

[dev]
  command = "npm run dev"   # Komenda do uruchamiania aplikacji lokalnie (opcjonalne)
